# Generated by Django 4.0.4 on 2022-05-13 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_directmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directmessage',
            old_name='receiver',
            new_name='recipient',
        ),
    ]
