# Generated by Django 4.0.4 on 2022-05-14 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_receiver_directmessage_recipient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directmessage',
            name='email',
        ),
        migrations.RemoveField(
            model_name='directmessage',
            name='name',
        ),
    ]
